### PR TITLE
 Removed whole menu from app.js and created a MainMenu component for it

### PR DESCRIPTION
**Pull request by addoasa**

### CODE REVIEW

**Comment by dkayzee** [comment]
looks good, couple questions.
1) any reason why you put a margin-top: 20px for .menu-colorful-bg?
2) if you look at the zeplin file, there is definitely a margin around .menu-bg, could you replicate that please.

**Comment by dkayzee** [comment]
also, routes need to be changed to /#menu/brunch or /#menu/desert, /#menu/drinks

**Review by dkayzee — CHANGES_REQUESTED** [review]
see comments above

**Comment by addoasa** [comment]
I will fix the margin. In the zepplin file the white menu back ground has some top padding from the main heading image. But i could not get that padding to work for whatever reason. 

Also why do the routes need to be changed again? They seem to be working fine for me

**Review by dkayzee — CHANGES_REQUESTED** [review]
when we do the scroller-router, the browser router will conflict so if we have just a menu/brunch etc etc, itll alleviate that problem

**Review by dkayzee — APPROVED** [review]

**Pull request merged**
